// Generated by piketype
// Source: action_lookup/piketype/table.py
// Do not edit by hand.

package table_pkg;

  localparam int LP_ADDR_WIDTH = 32;
  localparam int LP_ADDR_BYTE_COUNT = 4;

  typedef logic [LP_ADDR_WIDTH-1:0] addr_t;

  function automatic logic [LP_ADDR_WIDTH-1:0] pack_addr(addr_t a);
    return a;
  endfunction

  function automatic addr_t unpack_addr(logic [LP_ADDR_WIDTH-1:0] a);
    return a;
  endfunction

  localparam int LP_COHERENT_ID_WIDTH = 16;
  localparam int LP_COHERENT_ID_BYTE_COUNT = 2;

  typedef logic [LP_COHERENT_ID_WIDTH-1:0] coherent_id_t;

  function automatic logic [LP_COHERENT_ID_WIDTH-1:0] pack_coherent_id(coherent_id_t a);
    return a;
  endfunction

  function automatic coherent_id_t unpack_coherent_id(logic [LP_COHERENT_ID_WIDTH-1:0] a);
    return a;
  endfunction
endpackage
