// Generated by piketype
// Source: action_lookup/piketype/updates.py
// Do not edit by hand.

package updates_pkg;
  import table_pkg::LP_ADDR_WIDTH;
  import table_pkg::LP_COHERENT_ID_WIDTH;
  import table_pkg::addr_t;
  import table_pkg::coherent_id_t;
  import table_pkg::pack_addr;
  import table_pkg::pack_coherent_id;
  import table_pkg::unpack_addr;
  import table_pkg::unpack_coherent_id;

  localparam int LP_LL_TABLE_UPDATE_WIDTH = 81;
  localparam int LP_LL_TABLE_UPDATE_BYTE_COUNT = 12;

  typedef struct packed {
    addr_t next_addr;
    addr_t action_addr;
    coherent_id_t expected_id;
    logic [6:0] not_last_pad;
    logic not_last;
    logic [7:0] _align_pad;
  } ll_table_update_t;

  function automatic logic [LP_LL_TABLE_UPDATE_WIDTH-1:0] pack_ll_table_update(ll_table_update_t a);
    return {pack_addr(a.next_addr), pack_addr(a.action_addr), pack_coherent_id(a.expected_id), a.not_last};
  endfunction

  function automatic ll_table_update_t unpack_ll_table_update(logic [LP_LL_TABLE_UPDATE_WIDTH-1:0] a);
    ll_table_update_t result;
    result = '0;
    result.not_last = a[0:0];
    result.expected_id = unpack_coherent_id(a[16:1]);
    result.action_addr = unpack_addr(a[48:17]);
    result.next_addr = unpack_addr(a[80:49]);
    return result;
  endfunction

  localparam int LP_ACTION_WIDTH = 197;
  localparam int LP_ACTION_BYTE_COUNT = 27;

  typedef struct packed {
    logic [63:0] symbol;
    logic signed [63:0] price;
    logic signed [63:0] volume;
    logic [6:0] side_pad;
    logic side;
    logic [5:0] order_type_pad;
    logic [1:0] order_type;
    logic [5:0] life_time_pad;
    logic [1:0] life_time;
  } action_t;

  function automatic logic [LP_ACTION_WIDTH-1:0] pack_action(action_t a);
    return {a.symbol, a.price, a.volume, a.side, a.order_type, a.life_time};
  endfunction

  function automatic action_t unpack_action(logic [LP_ACTION_WIDTH-1:0] a);
    action_t result;
    result = '0;
    result.life_time = a[1:0];
    result.order_type = a[3:2];
    result.side = a[4:4];
    result.volume = signed'(a[68:5]);
    result.price = signed'(a[132:69]);
    result.symbol = a[196:133];
    return result;
  endfunction

  localparam int LP_ACTION_TABLE_UPDATE_WIDTH = 213;
  localparam int LP_ACTION_TABLE_UPDATE_BYTE_COUNT = 32;

  typedef struct packed {
    coherent_id_t stored_id;
    action_t action;
    logic [23:0] _align_pad;
  } action_table_update_t;

  function automatic logic [LP_ACTION_TABLE_UPDATE_WIDTH-1:0] pack_action_table_update(action_table_update_t a);
    return {pack_coherent_id(a.stored_id), pack_action(a.action)};
  endfunction

  function automatic action_table_update_t unpack_action_table_update(logic [LP_ACTION_TABLE_UPDATE_WIDTH-1:0] a);
    action_table_update_t result;
    result = '0;
    result.action = unpack_action(a[196:0]);
    result.stored_id = unpack_coherent_id(a[212:197]);
    return result;
  endfunction
endpackage
