"""Python backend."""

from __future__ import annotations

from pathlib import Path

from typist.backends.common.headers import render_header
from typist.ir.nodes import BinaryExprIR, ConstRefExprIR, IntLiteralExprIR, ModuleIR, RepoIR, UnaryExprIR
from typist.paths import py_module_output_path


def emit_py(repo: RepoIR) -> list[Path]:
    """Emit Python outputs."""
    written_paths: list[Path] = []
    repo_root = Path(repo.repo_root)
    py_root = repo_root / "gen" / "py"
    _ensure_package_init(py_root, written_paths)
    for module in repo.modules:
        output_path = py_module_output_path(
            repo_root=repo_root,
            module_path=repo_root / module.ref.repo_relative_path,
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)
        _ensure_package_chain(output_path.parent, py_root, written_paths)
        output_path.write_text(render_module_py(module), encoding="utf-8")
        written_paths.append(output_path)
    return written_paths


def render_module_py(module: ModuleIR) -> str:
    """Render a constant-only Python module."""
    header = render_header(source_paths=(module.ref.repo_relative_path,)).replace("//", "#")
    body_lines = [f"{const.name} = {_render_py_expr(expr=const.expr)}" for const in module.constants]
    return f"{header}\n" + "\n".join(body_lines) + "\n"


def _ensure_package_init(package_dir: Path, written_paths: list[Path]) -> None:
    """Create a package ``__init__.py`` if missing."""
    package_dir.mkdir(parents=True, exist_ok=True)
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("# Generated by typist\n# Do not edit by hand.\n", encoding="utf-8")
        written_paths.append(init_path)


def _ensure_package_chain(target_dir: Path, py_root: Path, written_paths: list[Path]) -> None:
    """Ensure all parent Python packages from the root to target exist."""
    current = py_root
    for part in target_dir.relative_to(py_root).parts:
        current = current / part
        _ensure_package_init(current, written_paths)


def _render_py_expr(*, expr: IntLiteralExprIR | ConstRefExprIR | UnaryExprIR | BinaryExprIR) -> str:
    """Render an expression into Python syntax."""
    match expr:
        case IntLiteralExprIR(value=value):
            return str(value)
        case ConstRefExprIR(name=name):
            return name
        case UnaryExprIR(op=op, operand=operand):
            return f"({op}{_render_py_expr(expr=operand)})"
        case BinaryExprIR(op=op, lhs=lhs, rhs=rhs):
            return f"({_render_py_expr(expr=lhs)} {op} {_render_py_expr(expr=rhs)})"
        case _:
            raise ValueError(f"unsupported Python expression node {type(expr).__name__}")
