"""Python backend."""

from __future__ import annotations

from math import ceil
from pathlib import Path

from typist.backends.common.headers import render_header
from typist.ir.nodes import BinaryExprIR, ConstRefExprIR, IntLiteralExprIR, ModuleIR, RepoIR, ScalarAliasIR, UnaryExprIR
from typist.paths import py_module_output_path


def emit_py(repo: RepoIR) -> list[Path]:
    """Emit Python outputs."""
    written_paths: list[Path] = []
    repo_root = Path(repo.repo_root)
    py_root = repo_root / "gen" / "py"
    _ensure_package_init(py_root, written_paths)
    for module in repo.modules:
        output_path = py_module_output_path(
            repo_root=repo_root,
            module_path=repo_root / module.ref.repo_relative_path,
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)
        _ensure_package_chain(output_path.parent, py_root, written_paths)
        output_path.write_text(render_module_py(module), encoding="utf-8")
        written_paths.append(output_path)
    return written_paths


def render_module_py(module: ModuleIR) -> str:
    """Render a constant-only Python module."""
    header = render_header(source_paths=(module.ref.repo_relative_path,)).replace("//", "#")
    body_lines: list[str] = []
    if module.types:
        body_lines.append("from __future__ import annotations")
        body_lines.append("")
    body_lines.extend(f"{const.name} = {_render_py_expr(expr=const.expr)}" for const in module.constants)
    if module.constants and module.types:
        body_lines.append("")
    for index, type_ir in enumerate(module.types):
        if index > 0:
            body_lines.append("")
        body_lines.extend(_render_py_scalar_alias(type_ir=type_ir))
    return f"{header}\n" + "\n".join(body_lines) + "\n"


def _ensure_package_init(package_dir: Path, written_paths: list[Path]) -> None:
    """Create a package ``__init__.py`` if missing."""
    package_dir.mkdir(parents=True, exist_ok=True)
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("# Generated by typist\n# Do not edit by hand.\n", encoding="utf-8")
        written_paths.append(init_path)


def _ensure_package_chain(target_dir: Path, py_root: Path, written_paths: list[Path]) -> None:
    """Ensure all parent Python packages from the root to target exist."""
    current = py_root
    for part in target_dir.relative_to(py_root).parts:
        current = current / part
        _ensure_package_init(current, written_paths)


def _render_py_expr(*, expr: IntLiteralExprIR | ConstRefExprIR | UnaryExprIR | BinaryExprIR) -> str:
    """Render an expression into Python syntax."""
    match expr:
        case IntLiteralExprIR(value=value):
            return str(value)
        case ConstRefExprIR(name=name):
            return name
        case UnaryExprIR(op=op, operand=operand):
            return f"({op}{_render_py_expr(expr=operand)})"
        case BinaryExprIR(op=op, lhs=lhs, rhs=rhs):
            return f"({_render_py_expr(expr=lhs)} {op} {_render_py_expr(expr=rhs)})"
        case _:
            raise ValueError(f"unsupported Python expression node {type(expr).__name__}")


def _render_py_scalar_alias(*, type_ir: ScalarAliasIR) -> list[str]:
    """Render a Python scalar wrapper class."""
    class_name = _scalar_class_name(type_ir.name)
    byte_count = ceil(type_ir.resolved_width / 8)
    lines = [
        f"class {class_name}:",
        f"    WIDTH = {type_ir.resolved_width}",
        f"    SIGNED = {type_ir.signed}",
        f"    BYTE_COUNT = {byte_count}",
    ]
    if type_ir.resolved_width <= 64:
        if type_ir.signed:
            minimum = -(2 ** (type_ir.resolved_width - 1))
            maximum = 2 ** (type_ir.resolved_width - 1) - 1
            mask = (1 << type_ir.resolved_width) - 1
            sign_bit = 1 << (type_ir.resolved_width - 1)
            lines.extend(
                [
                    f"    MIN_VALUE = {minimum}",
                    f"    MAX_VALUE = {maximum}",
                    f"    MASK = {mask}",
                    f"    SIGN_BIT = {sign_bit}",
                    "",
                    "    def __init__(self, value: int = 0) -> None:",
                    '        if not isinstance(value, int):',
                    f'            raise TypeError("{class_name} value must be int")',
                    "        if value < self.MIN_VALUE or value > self.MAX_VALUE:",
                    f'            raise ValueError("{class_name} value out of range")',
                    "        self.value = value",
                    "",
                    "    def to_bytes(self) -> bytes:",
                    '        return (self.value & self.MASK).to_bytes(self.BYTE_COUNT, "little", signed=False)',
                    "",
                    "    @classmethod",
                    f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
                    '        if not isinstance(data, (bytes, bytearray)):',
                    f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
                    "        raw = bytes(data)",
                    "        if len(raw) != cls.BYTE_COUNT:",
                    f'            raise ValueError("{class_name}.from_bytes size mismatch")',
                    '        value = int.from_bytes(raw, "little", signed=False)',
                    "        if value > cls.MASK:",
                    f'            raise ValueError("{class_name}.from_bytes value out of range")',
                    "        signed_value = value - (1 << cls.WIDTH) if (value & cls.SIGN_BIT) else value",
                    "        return cls(signed_value)",
                    "",
                    f'    def clone(self) -> "{class_name}":',
                    "        return type(self)(self.value)",
                    "",
                    "    def __int__(self) -> int:",
                    "        return self.value",
                    "",
                    "    def __index__(self) -> int:",
                    "        return self.value",
                    "",
                    "    def __eq__(self, other: object) -> bool:",
                    "        if isinstance(other, type(self)):",
                    "            return self.value == other.value",
                    "        if isinstance(other, int):",
                    "            return self.value == other",
                    "        return NotImplemented",
                    "",
                    "    def __repr__(self) -> str:",
                    f'        return f"{class_name}(value={{self.value!r}})"',
                ]
            )
        else:
            maximum = 2 ** type_ir.resolved_width - 1
            lines.extend(
                [
                    "    MIN_VALUE = 0",
                    f"    MAX_VALUE = {maximum}",
                    "",
                    "    def __init__(self, value: int = 0) -> None:",
                    '        if not isinstance(value, int):',
                    f'            raise TypeError("{class_name} value must be int")',
                    "        if value < self.MIN_VALUE or value > self.MAX_VALUE:",
                    f'            raise ValueError("{class_name} value out of range")',
                    "        self.value = value",
                    "",
                    "    def to_bytes(self) -> bytes:",
                    '        return self.value.to_bytes(self.BYTE_COUNT, "little", signed=False)',
                    "",
                    "    @classmethod",
                    f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
                    '        if not isinstance(data, (bytes, bytearray)):',
                    f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
                    "        raw = bytes(data)",
                    "        if len(raw) != cls.BYTE_COUNT:",
                    f'            raise ValueError("{class_name}.from_bytes size mismatch")',
                    '        return cls(int.from_bytes(raw, "little", signed=False))',
                    "",
                    f'    def clone(self) -> "{class_name}":',
                    "        return type(self)(self.value)",
                    "",
                    "    def __int__(self) -> int:",
                    "        return self.value",
                    "",
                    "    def __index__(self) -> int:",
                    "        return self.value",
                    "",
                    "    def __eq__(self, other: object) -> bool:",
                    "        if isinstance(other, type(self)):",
                    "            return self.value == other.value",
                    "        if isinstance(other, int):",
                    "            return self.value == other",
                    "        return NotImplemented",
                    "",
                    "    def __repr__(self) -> str:",
                    f'        return f"{class_name}(value={{self.value!r}})"',
                ]
            )
    else:
        maximum = 2 ** type_ir.resolved_width - 1
        lines.extend(
            [
                f"    MAX_VALUE = {maximum}",
                "",
                "    def __init__(self, value: bytes | bytearray | int = b'') -> None:",
                "        if isinstance(value, int):",
                "            if value < 0 or value > self.MAX_VALUE:",
                f'                raise ValueError("{class_name} value out of range")',
                '            self.value = value.to_bytes(self.BYTE_COUNT, "little", signed=False)',
                "            return",
                '        if not isinstance(value, (bytes, bytearray)):',
                f'            raise TypeError("{class_name} value must be bytes, bytearray, or int")',
                "        raw = bytes(value)",
                "        if len(raw) == 0:",
                '            raw = b"\\x00" * self.BYTE_COUNT',
                "        if len(raw) != self.BYTE_COUNT:",
                f'            raise ValueError("{class_name} value size mismatch")',
                "        self.value = raw",
                "",
                "    def to_bytes(self) -> bytes:",
                "        return self.value",
                "",
                "    @classmethod",
                f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
                '        if not isinstance(data, (bytes, bytearray)):',
                f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
                "        return cls(bytes(data))",
                "",
                f'    def clone(self) -> "{class_name}":',
                "        return type(self)(self.value)",
                "",
                "    def __eq__(self, other: object) -> bool:",
                "        if isinstance(other, type(self)):",
                "            return self.value == other.value",
                "        if isinstance(other, (bytes, bytearray)):",
                "            return self.value == bytes(other)",
                "        return NotImplemented",
                "",
                "    def __repr__(self) -> str:",
                f'        return f"{class_name}(value={{self.value!r}})"',
            ]
        )
    return lines


def _scalar_class_name(type_name: str) -> str:
    """Convert a scalar alias name to its software wrapper class name."""
    if type_name.endswith("_t"):
        return f"{type_name[:-2]}_ct"
    return f"{type_name}_ct"
