"""Runtime backend."""

from __future__ import annotations

from pathlib import Path

from piketype.backends.common.headers import render_header
from piketype.ir.nodes import RepoIR
from piketype.paths import (
    cpp_runtime_header_output_path,
    cpp_runtime_source_output_path,
    py_runtime_output_path,
    sv_runtime_output_path,
)


def emit_runtime(repo: RepoIR) -> list[Path]:
    """Emit shared runtime outputs."""
    repo_root = Path(repo.repo_root)
    written_paths: list[Path] = []

    sv_output_path = sv_runtime_output_path(repo_root=repo_root)
    sv_output_path.parent.mkdir(parents=True, exist_ok=True)
    sv_output_path.write_text(render_runtime_sv(), encoding="utf-8")
    written_paths.append(sv_output_path)

    py_output_path = py_runtime_output_path(repo_root=repo_root)
    py_output_path.parent.mkdir(parents=True, exist_ok=True)
    init_path = py_output_path.parent / "__init__.py"
    if not init_path.exists():
        init_path.write_text("# Generated by piketype\n# Do not edit by hand.\n", encoding="utf-8")
        written_paths.append(init_path)
    py_output_path.write_text(render_runtime_py(), encoding="utf-8")
    written_paths.append(py_output_path)

    cpp_header_path = cpp_runtime_header_output_path(repo_root=repo_root)
    cpp_source_path = cpp_runtime_source_output_path(repo_root=repo_root)
    cpp_header_path.parent.mkdir(parents=True, exist_ok=True)
    cpp_header_path.write_text(render_runtime_hpp(), encoding="utf-8")
    cpp_source_path.write_text(render_runtime_cpp(), encoding="utf-8")
    written_paths.extend([cpp_header_path, cpp_source_path])

    return written_paths


def render_runtime_sv() -> str:
    """Render the milestone-01 runtime placeholder package."""
    header = render_header(source_paths=("<runtime>",))
    return f"{header}\npackage piketype_runtime_pkg;\nendpackage\n"


def render_runtime_py() -> str:
    """Render the milestone-02 Python runtime placeholder."""
    header = render_header(source_paths=("<runtime>",)).replace("//", "#")
    return f"{header}\nVERBOSE = False\n"


def render_runtime_hpp() -> str:
    """Render the milestone-02 C++ runtime header placeholder."""
    header = render_header(source_paths=("<runtime>",))
    return (
        f"{header}\n"
        "#ifndef PIKETYPE_RUNTIME_HPP\n"
        "#define PIKETYPE_RUNTIME_HPP\n\n"
        "namespace piketype_runtime {\n\n"
        "inline constexpr bool VERBOSE_DEFAULT = false;\n\n"
        "}  // namespace piketype_runtime\n\n"
        "#endif  // PIKETYPE_RUNTIME_HPP\n"
    )


def render_runtime_cpp() -> str:
    """Render the milestone-02 C++ runtime source placeholder."""
    header = render_header(source_paths=("<runtime>",))
    return f'{header}\n#include "piketype_runtime.hpp"\n'
