# Generated by piketype
# Source: action_lookup/piketype/table.py
# Do not edit by hand.

from __future__ import annotations

class Addr:
    WIDTH = 32
    SIGNED = False
    BYTE_COUNT = 4
    MIN_VALUE = 0
    MAX_VALUE = 4294967295

    def __init__(self, value: int = 0) -> None:
        if not isinstance(value, int):
            raise TypeError("Addr value must be int")
        if value < self.MIN_VALUE or value > self.MAX_VALUE:
            raise ValueError("Addr value out of range")
        self.value = value

    def pack(self) -> int:
        return self.value

    @classmethod
    def unpack(cls, packed: int) -> "Addr":
        return cls(packed & cls.MAX_VALUE)

    def to_lv(self) -> int:
        return int.from_bytes(self.to_bytes(), "big", signed=False)

    @classmethod
    def from_lv(cls, value: int) -> "Addr":
        return cls.from_bytes((value & ((1 << (cls.BYTE_COUNT * 8)) - 1)).to_bytes(cls.BYTE_COUNT, "big", signed=False))

    def to_bytes(self) -> bytes:
        return self.value.to_bytes(self.BYTE_COUNT, "big", signed=False)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "Addr":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("Addr.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("Addr.from_bytes size mismatch")
        value = int.from_bytes(raw, "big", signed=False) & cls.MAX_VALUE
        return cls(value)

    def clone(self) -> "Addr":
        return type(self)(self.value)

    def compare(self, other: object, msg: str = "") -> None:
        assert isinstance(other, Addr), "Expected Addr, got " + str(type(other))
        if self.value != other.value:
            prefix = msg + ": " if msg else ""
            raise AssertionError(prefix + repr(self) + " != " + repr(other))

    def __int__(self) -> int:
        return self.value

    def __index__(self) -> int:
        return self.value

    def __eq__(self, other: object) -> bool:
        if isinstance(other, type(self)):
            return self.value == other.value
        if isinstance(other, int):
            return self.value == other
        return NotImplemented

    def __repr__(self) -> str:
        return f"Addr(value={self.value!r})"

class CoherentId:
    WIDTH = 16
    SIGNED = False
    BYTE_COUNT = 2
    MIN_VALUE = 0
    MAX_VALUE = 65535

    def __init__(self, value: int = 0) -> None:
        if not isinstance(value, int):
            raise TypeError("CoherentId value must be int")
        if value < self.MIN_VALUE or value > self.MAX_VALUE:
            raise ValueError("CoherentId value out of range")
        self.value = value

    def pack(self) -> int:
        return self.value

    @classmethod
    def unpack(cls, packed: int) -> "CoherentId":
        return cls(packed & cls.MAX_VALUE)

    def to_lv(self) -> int:
        return int.from_bytes(self.to_bytes(), "big", signed=False)

    @classmethod
    def from_lv(cls, value: int) -> "CoherentId":
        return cls.from_bytes((value & ((1 << (cls.BYTE_COUNT * 8)) - 1)).to_bytes(cls.BYTE_COUNT, "big", signed=False))

    def to_bytes(self) -> bytes:
        return self.value.to_bytes(self.BYTE_COUNT, "big", signed=False)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "CoherentId":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("CoherentId.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("CoherentId.from_bytes size mismatch")
        value = int.from_bytes(raw, "big", signed=False) & cls.MAX_VALUE
        return cls(value)

    def clone(self) -> "CoherentId":
        return type(self)(self.value)

    def compare(self, other: object, msg: str = "") -> None:
        assert isinstance(other, CoherentId), "Expected CoherentId, got " + str(type(other))
        if self.value != other.value:
            prefix = msg + ": " if msg else ""
            raise AssertionError(prefix + repr(self) + " != " + repr(other))

    def __int__(self) -> int:
        return self.value

    def __index__(self) -> int:
        return self.value

    def __eq__(self, other: object) -> bool:
        if isinstance(other, type(self)):
            return self.value == other.value
        if isinstance(other, int):
            return self.value == other
        return NotImplemented

    def __repr__(self) -> str:
        return f"CoherentId(value={self.value!r})"
