"""Generated file header helpers."""

from __future__ import annotations

from collections.abc import Iterable


def render_header(*, source_paths: Iterable[str]) -> str:
    """Render a stable generated-file header."""
    source_lines = "\n".join(f"// Source: {source_path}" for source_path in source_paths)
    return (
        "// Generated by typist\n"
        f"{source_lines}\n"
        "// Do not edit by hand.\n"
    )
