// Generated by piketype
// Source: action_lookup/piketype/table.py
// Do not edit by hand.

#pragma once

#include <cstdint>
#include <array>
#include <cstddef>
#include <cstring>
#include <span>
#include <stdexcept>

namespace action_lookup::table {

class Addr {
public:
    static constexpr size_t WIDTH      = 32;
    static constexpr bool   SIGNED     = false;
    static constexpr size_t BYTE_COUNT = 4;
    using value_type                   = uint32_t;

    value_type value;

    Addr()
        : value(0) {}
    Addr(value_type value_in)
        : value(value_in) {}

    [[nodiscard]] std::array<uint8_t, BYTE_COUNT> to_bytes() const {
        std::array<uint8_t, BYTE_COUNT> out{};
        pack_into(out.data());
        return out;
    }

    [[nodiscard]] static Addr from_bytes(std::span<const uint8_t> bytes) {
        if (bytes.size() != BYTE_COUNT) {
            throw std::invalid_argument("byte width mismatch");
        }
        Addr result;
        result.unpack_from(bytes.data());
        return result;
    }

    void pack_into(uint8_t* dst) const {
        {
            uint32_t be = __builtin_bswap32(value);
            std::memcpy(dst + 0, &be, 4);
        }
    }

    void unpack_from(const uint8_t* src) {
        uint32_t be;
        std::memcpy(&be, src + 0, 4);
        uint64_t bits = __builtin_bswap32(be);
        value         = static_cast<value_type>(bits);
    }

    operator value_type() const {
        return value;
    }
    bool operator==(const Addr& other) const = default;
};

class CoherentId {
public:
    static constexpr size_t WIDTH      = 16;
    static constexpr bool   SIGNED     = false;
    static constexpr size_t BYTE_COUNT = 2;
    using value_type                   = uint16_t;

    value_type value;

    CoherentId()
        : value(0) {}
    CoherentId(value_type value_in)
        : value(value_in) {}

    [[nodiscard]] std::array<uint8_t, BYTE_COUNT> to_bytes() const {
        std::array<uint8_t, BYTE_COUNT> out{};
        pack_into(out.data());
        return out;
    }

    [[nodiscard]] static CoherentId from_bytes(std::span<const uint8_t> bytes) {
        if (bytes.size() != BYTE_COUNT) {
            throw std::invalid_argument("byte width mismatch");
        }
        CoherentId result;
        result.unpack_from(bytes.data());
        return result;
    }

    void pack_into(uint8_t* dst) const {
        {
            uint16_t be = __builtin_bswap16(value);
            std::memcpy(dst + 0, &be, 2);
        }
    }

    void unpack_from(const uint8_t* src) {
        uint16_t be;
        std::memcpy(&be, src + 0, 2);
        uint64_t bits = __builtin_bswap16(be);
        value         = static_cast<value_type>(bits);
    }

    operator value_type() const {
        return value;
    }
    bool operator==(const CoherentId& other) const = default;
};

}  // namespace action_lookup::table
