// Generated by piketype
// Source: action_lookup/piketype/updates.py
// Do not edit by hand.

#pragma once

#include <cstdint>
#include <array>
#include <cstddef>
#include <cstring>
#include <span>
#include <stdexcept>
#include "action_lookup/piketype/table_types.hpp"

namespace action_lookup::updates {

class LlTableUpdate {
public:
    static constexpr size_t WIDTH      = 81;
    static constexpr size_t BYTE_COUNT = 12;
    table::Addr             next_addr{};
    table::Addr             action_addr{};
    table::CoherentId       expected_id{};
    uint8_t                 not_last = 0;

    LlTableUpdate() = default;

    [[nodiscard]] std::array<uint8_t, BYTE_COUNT> to_bytes() const {
        std::array<uint8_t, BYTE_COUNT> out{};
        pack_into(out.data());
        return out;
    }

    [[nodiscard]] static LlTableUpdate from_bytes(std::span<const uint8_t> bytes) {
        if (bytes.size() != BYTE_COUNT) {
            throw std::invalid_argument("byte width mismatch");
        }
        LlTableUpdate result;
        result.unpack_from(bytes.data());
        return result;
    }

    void pack_into(uint8_t* dst) const {
        next_addr.pack_into(dst + 0);
        action_addr.pack_into(dst + 4);
        expected_id.pack_into(dst + 8);
        if (not_last > static_cast<uint8_t>(1U)) {
            throw std::out_of_range("not_last value out of range");
        }
        dst[10] = not_last;
        std::memset(dst + 11, 0, 1);
    }

    void unpack_from(const uint8_t* src) {
        next_addr.unpack_from(src + 0);
        action_addr.unpack_from(src + 4);
        expected_id.unpack_from(src + 8);
        {
            uint64_t bits = src[10];
            bits &= 1U;
            not_last = static_cast<uint8_t>(bits);
        }
    }

    bool operator==(const LlTableUpdate& other) const = default;
};

class Action {
public:
    static constexpr size_t WIDTH      = 197;
    static constexpr size_t BYTE_COUNT = 27;
    uint64_t                symbol     = 0;
    int64_t                 price      = 0;
    int64_t                 volume     = 0;
    uint8_t                 side       = 0;
    uint8_t                 order_type = 0;
    uint8_t                 life_time  = 0;

    Action() = default;

    [[nodiscard]] std::array<uint8_t, BYTE_COUNT> to_bytes() const {
        std::array<uint8_t, BYTE_COUNT> out{};
        pack_into(out.data());
        return out;
    }

    [[nodiscard]] static Action from_bytes(std::span<const uint8_t> bytes) {
        if (bytes.size() != BYTE_COUNT) {
            throw std::invalid_argument("byte width mismatch");
        }
        Action result;
        result.unpack_from(bytes.data());
        return result;
    }

    void pack_into(uint8_t* dst) const {
        {
            uint64_t be = __builtin_bswap64(symbol);
            std::memcpy(dst + 0, &be, 8);
        }
        {
            uint64_t be = __builtin_bswap64(static_cast<uint64_t>(price));
            std::memcpy(dst + 8, &be, 8);
        }
        {
            uint64_t be = __builtin_bswap64(static_cast<uint64_t>(volume));
            std::memcpy(dst + 16, &be, 8);
        }
        if (side > static_cast<uint8_t>(1U)) {
            throw std::out_of_range("side value out of range");
        }
        dst[24] = side;
        if (order_type > static_cast<uint8_t>(3U)) {
            throw std::out_of_range("order_type value out of range");
        }
        dst[25] = order_type;
        if (life_time > static_cast<uint8_t>(3U)) {
            throw std::out_of_range("life_time value out of range");
        }
        dst[26] = life_time;
    }

    void unpack_from(const uint8_t* src) {
        {
            uint64_t raw;
            std::memcpy(&raw, src + 0, 8);
            symbol = __builtin_bswap64(raw);
        }
        {
            uint64_t raw;
            std::memcpy(&raw, src + 8, 8);
            price = static_cast<int64_t>(__builtin_bswap64(raw));
        }
        {
            uint64_t raw;
            std::memcpy(&raw, src + 16, 8);
            volume = static_cast<int64_t>(__builtin_bswap64(raw));
        }
        {
            uint64_t bits = src[24];
            bits &= 1U;
            side = static_cast<uint8_t>(bits);
        }
        {
            uint64_t bits = src[25];
            bits &= 3U;
            order_type = static_cast<uint8_t>(bits);
        }
        {
            uint64_t bits = src[26];
            bits &= 3U;
            life_time = static_cast<uint8_t>(bits);
        }
    }

    bool operator==(const Action& other) const = default;
};

class ActionTableUpdate {
public:
    static constexpr size_t WIDTH      = 213;
    static constexpr size_t BYTE_COUNT = 32;
    table::CoherentId       stored_id{};
    Action                  action{};

    ActionTableUpdate() = default;

    [[nodiscard]] std::array<uint8_t, BYTE_COUNT> to_bytes() const {
        std::array<uint8_t, BYTE_COUNT> out{};
        pack_into(out.data());
        return out;
    }

    [[nodiscard]] static ActionTableUpdate from_bytes(std::span<const uint8_t> bytes) {
        if (bytes.size() != BYTE_COUNT) {
            throw std::invalid_argument("byte width mismatch");
        }
        ActionTableUpdate result;
        result.unpack_from(bytes.data());
        return result;
    }

    void pack_into(uint8_t* dst) const {
        stored_id.pack_into(dst + 0);
        action.pack_into(dst + 2);
        std::memset(dst + 29, 0, 3);
    }

    void unpack_from(const uint8_t* src) {
        stored_id.unpack_from(src + 0);
        action.unpack_from(src + 2);
    }

    bool operator==(const ActionTableUpdate& other) const = default;
};

}  // namespace action_lookup::updates
