"""Python backend.

Renders generated Python modules via Jinja2 templates. The Python
emitter holds no semantic logic; all numeric primitives and
pre-rendered fragments are computed by ``build_module_view_py`` in
``view.py``, and the templates in ``templates/`` render structure
and syntax.
"""

from __future__ import annotations

from pathlib import Path

from piketype.backends.common.headers import render_header
from piketype.backends.common.render import make_environment, render
from piketype.backends.py.view import build_module_view_py
from piketype.ir.nodes import ModuleIR, RepoIR, TypeDefIR
from piketype.ir.repo_index import build_repo_type_index
from piketype.paths import py_module_output_path


def emit_py(repo: RepoIR) -> list[Path]:
    """Emit Python outputs."""
    written_paths: list[Path] = []
    repo_root = Path(repo.repo_root)
    py_root = repo_root / "gen" / "py"
    _ensure_package_init(py_root, written_paths)
    env = make_environment(package="piketype.backends.py")
    repo_type_index = build_repo_type_index(repo)
    for module in repo.modules:
        output_path = py_module_output_path(
            repo_root=repo_root,
            module_path=repo_root / module.ref.repo_relative_path,
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)
        _ensure_package_chain(output_path.parent, py_root, written_paths)
        output_path.write_text(
            _render_module(module=module, env=env, repo_type_index=repo_type_index),
            encoding="utf-8",
        )
        written_paths.append(output_path)
    return written_paths


def _render_module(*, module: ModuleIR, env: object, repo_type_index: dict[tuple[str, str], TypeDefIR]) -> str:
    """Build the view model and render module.j2."""
    header = render_header(source_paths=(module.ref.repo_relative_path,)).replace("//", "#")
    view = build_module_view_py(module=module, header=header, repo_type_index=repo_type_index)
    return render(env=env, template_name="module.j2", context=view)


def _ensure_package_init(package_dir: Path, written_paths: list[Path]) -> None:
    """Create a package ``__init__.py`` if missing."""
    package_dir.mkdir(parents=True, exist_ok=True)
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("# Generated by piketype\n# Do not edit by hand.\n", encoding="utf-8")
        written_paths.append(init_path)


def _ensure_package_chain(target_dir: Path, py_root: Path, written_paths: list[Path]) -> None:
    """Ensure all parent Python packages from the root to target exist."""
    current = py_root
    for part in target_dir.relative_to(py_root).parts:
        current = current / part
        _ensure_package_init(current, written_paths)
