"""Python backend."""

from __future__ import annotations

from pathlib import Path

from piketype.backends.common.headers import render_header
from piketype.backends.common.render import make_environment, render
from piketype.backends.py.view import ModuleView, build_module_view_py
from piketype.ir.nodes import (
    BinaryExprIR,
    ConstRefExprIR,
    EnumIR,
    ExprIR,
    FieldTypeIR,
    FlagsIR,
    IntLiteralExprIR,
    ModuleIR,
    RepoIR,
    ScalarAliasIR,
    ScalarTypeSpecIR,
    StructIR,
    StructFieldIR,
    TypeDefIR,
    TypeRefIR,
    UnaryExprIR,
    byte_count,
)
from piketype.paths import py_module_output_path


def emit_py(repo: RepoIR) -> list[Path]:
    """Emit Python outputs."""
    written_paths: list[Path] = []
    repo_root = Path(repo.repo_root)
    py_root = repo_root / "gen" / "py"
    _ensure_package_init(py_root, written_paths)
    env = make_environment(package="piketype.backends.py")
    for module in repo.modules:
        output_path = py_module_output_path(
            repo_root=repo_root,
            module_path=repo_root / module.ref.repo_relative_path,
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)
        _ensure_package_chain(output_path.parent, py_root, written_paths)
        output_path.write_text(render_module_py(module=module, env=env), encoding="utf-8")
        written_paths.append(output_path)
    return written_paths


def render_module_py(*, module: ModuleIR, env: object | None = None) -> str:
    """Render a Python module via the module.j2 Jinja template.

    During the FR-6 sub-step migration (T-08..T-11) the not-yet-templated
    portion of the body is passed through as ``body_lines`` on the view
    model. T-08 (this commit) lands the module-level skeleton: header,
    import block, and body passthrough. Class scaffolding, helper-method
    skeletons, and expression fragments are migrated in T-09..T-11.
    """
    header = render_header(source_paths=(module.ref.repo_relative_path,)).replace("//", "#")
    body_lines = _legacy_render_py_body_lines(module)
    view = build_module_view_py(module=module, header=header)
    view = ModuleView(
        header=view.header,
        has_types=view.has_types,
        has_structs=view.has_structs,
        has_enums=view.has_enums,
        has_flags=view.has_flags,
        constants=view.constants,
        types=view.types,
        body_lines=tuple(body_lines),
        has_body_lines=bool(body_lines),
    )
    if env is None:
        env = make_environment(package="piketype.backends.py")
    return render(env=env, template_name="module.j2", context=view)


def _legacy_render_py_body_lines(module: ModuleIR) -> list[str]:
    """Compute the post-header body lines exactly as the legacy emitter did.

    This is the transitional helper that drives the InlineFragmentView
    passthrough (FR-7 byte parity) during T-08..T-11. Each subsequent
    migration commit replaces a slice of this output with structured
    template rendering until ``body_lines`` is empty in T-12.
    """
    type_index = {type_ir.name: type_ir for type_ir in module.types}
    has_types = bool(module.types)
    has_structs = any(isinstance(type_ir, StructIR) for type_ir in module.types)
    has_enums = any(isinstance(type_ir, EnumIR) for type_ir in module.types)
    body_lines: list[str] = []
    if has_types:
        body_lines.append("from __future__ import annotations")
        if has_structs:
            body_lines.append("")
            body_lines.append("from dataclasses import dataclass, field")
        if has_enums:
            body_lines.append("")
            body_lines.append("from enum import IntEnum")
        body_lines.append("")
    body_lines.extend(f"{const.name} = {_render_py_expr(expr=const.expr)}" for const in module.constants)
    if module.constants and module.types:
        body_lines.append("")
    for index, type_ir in enumerate(module.types):
        if index > 0:
            body_lines.append("")
        if isinstance(type_ir, ScalarAliasIR):
            body_lines.extend(_render_py_scalar_alias(type_ir=type_ir))
        elif isinstance(type_ir, StructIR):
            body_lines.extend(_render_py_struct(type_ir=type_ir, type_index=type_index))
        elif isinstance(type_ir, FlagsIR):
            body_lines.extend(_render_py_flags(type_ir=type_ir))
        elif isinstance(type_ir, EnumIR):
            body_lines.extend(_render_py_enum(type_ir=type_ir))
    return body_lines


def _ensure_package_init(package_dir: Path, written_paths: list[Path]) -> None:
    """Create a package ``__init__.py`` if missing."""
    package_dir.mkdir(parents=True, exist_ok=True)
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("# Generated by piketype\n# Do not edit by hand.\n", encoding="utf-8")
        written_paths.append(init_path)


def _ensure_package_chain(target_dir: Path, py_root: Path, written_paths: list[Path]) -> None:
    """Ensure all parent Python packages from the root to target exist."""
    current = py_root
    for part in target_dir.relative_to(py_root).parts:
        current = current / part
        _ensure_package_init(current, written_paths)


def _render_py_expr(*, expr: ExprIR) -> str:
    """Render an expression into Python syntax."""
    match expr:
        case IntLiteralExprIR(value=value):
            return str(value)
        case ConstRefExprIR(name=name):
            return name
        case UnaryExprIR(op=op, operand=operand):
            return f"({op}{_render_py_expr(expr=operand)})"
        case BinaryExprIR(op=op, lhs=lhs, rhs=rhs):
            return f"({_render_py_expr(expr=lhs)} {op} {_render_py_expr(expr=rhs)})"
        case _:
            raise ValueError(f"unsupported Python expression node {type(expr).__name__}")


def _render_py_scalar_alias(*, type_ir: ScalarAliasIR) -> list[str]:
    """Render a Python scalar wrapper class."""
    class_name = _type_class_name(type_ir.name)
    bc = byte_count(type_ir.resolved_width)
    lines = [
        f"class {class_name}:",
        f"    WIDTH = {type_ir.resolved_width}",
        f"    SIGNED = {type_ir.signed}",
        f"    BYTE_COUNT = {bc}",
    ]
    if type_ir.resolved_width <= 64:
        if type_ir.signed:
            minimum = -(2 ** (type_ir.resolved_width - 1))
            maximum = 2 ** (type_ir.resolved_width - 1) - 1
            mask = (1 << type_ir.resolved_width) - 1
            sign_bit = 1 << (type_ir.resolved_width - 1)
            pad_bits = bc * 8 - type_ir.resolved_width
            lines.extend(
                [
                    f"    MIN_VALUE = {minimum}",
                    f"    MAX_VALUE = {maximum}",
                    f"    MASK = {mask}",
                    f"    SIGN_BIT = {sign_bit}",
                    "",
                    "    def __init__(self, value: int = 0) -> None:",
                    '        if not isinstance(value, int):',
                    f'            raise TypeError("{class_name} value must be int")',
                    "        if value < self.MIN_VALUE or value > self.MAX_VALUE:",
                    f'            raise ValueError("{class_name} value out of range")',
                    "        self.value = value",
                    "",
                    "    def _to_packed_int(self) -> int:",
                    "        return self.value & self.MASK",
                    "",
                    "    @classmethod",
                    f'    def _from_packed_int(cls, packed: int) -> "{class_name}":',
                    "        value = packed & cls.MASK",
                    "        signed_value = value - (1 << cls.WIDTH) if (value & cls.SIGN_BIT) else value",
                    "        return cls(signed_value)",
                    "",
                    "    def to_bytes(self) -> bytes:",
                    "        mask = self.MASK",
                    "        packed = self.value & mask",
                    "        if self.value < 0:",
                    f"            packed |= ((1 << (self.BYTE_COUNT * 8)) - 1) ^ mask",
                    '        return packed.to_bytes(self.BYTE_COUNT, "big", signed=False)',
                    "",
                    "    @classmethod",
                    f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
                    '        if not isinstance(data, (bytes, bytearray)):',
                    f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
                    "        raw = bytes(data)",
                    "        if len(raw) != cls.BYTE_COUNT:",
                    f'            raise ValueError("{class_name}.from_bytes size mismatch")',
                    '        raw_int = int.from_bytes(raw, "big", signed=False)',
                    "        data_bits = raw_int & cls.MASK",
                    f"        padding = raw_int >> cls.WIDTH",
                    "        sign_bit = (data_bits >> (cls.WIDTH - 1)) & 1",
                    f"        expected_padding = ((1 << {pad_bits}) - 1) if sign_bit else 0",
                    "        if padding != expected_padding:",
                    f'            raise ValueError("{class_name}.from_bytes signed padding mismatch")',
                    "        return cls._from_packed_int(data_bits)",
                    "",
                    f'    def clone(self) -> "{class_name}":',
                    "        return type(self)(self.value)",
                    "",
                    "    def __int__(self) -> int:",
                    "        return self.value",
                    "",
                    "    def __index__(self) -> int:",
                    "        return self.value",
                    "",
                    "    def __eq__(self, other: object) -> bool:",
                    "        if isinstance(other, type(self)):",
                    "            return self.value == other.value",
                    "        if isinstance(other, int):",
                    "            return self.value == other",
                    "        return NotImplemented",
                    "",
                    "    def __repr__(self) -> str:",
                    f'        return f"{class_name}(value={{self.value!r}})"',
                ]
            )
        else:
            maximum = 2 ** type_ir.resolved_width - 1
            lines.extend(
                [
                    "    MIN_VALUE = 0",
                    f"    MAX_VALUE = {maximum}",
                    "",
                    "    def __init__(self, value: int = 0) -> None:",
                    '        if not isinstance(value, int):',
                    f'            raise TypeError("{class_name} value must be int")',
                    "        if value < self.MIN_VALUE or value > self.MAX_VALUE:",
                    f'            raise ValueError("{class_name} value out of range")',
                    "        self.value = value",
                    "",
                    "    def _to_packed_int(self) -> int:",
                    "        return self.value",
                    "",
                    "    @classmethod",
                    f'    def _from_packed_int(cls, packed: int) -> "{class_name}":',
                    "        return cls(packed)",
                    "",
                    "    def to_bytes(self) -> bytes:",
                    '        return self.value.to_bytes(self.BYTE_COUNT, "big", signed=False)',
                    "",
                    "    @classmethod",
                    f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
                    '        if not isinstance(data, (bytes, bytearray)):',
                    f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
                    "        raw = bytes(data)",
                    "        if len(raw) != cls.BYTE_COUNT:",
                    f'            raise ValueError("{class_name}.from_bytes size mismatch")',
                    "        value = int.from_bytes(raw, \"big\", signed=False) & cls.MAX_VALUE",
                    "        return cls(value)",
                    "",
                    f'    def clone(self) -> "{class_name}":',
                    "        return type(self)(self.value)",
                    "",
                    "    def __int__(self) -> int:",
                    "        return self.value",
                    "",
                    "    def __index__(self) -> int:",
                    "        return self.value",
                    "",
                    "    def __eq__(self, other: object) -> bool:",
                    "        if isinstance(other, type(self)):",
                    "            return self.value == other.value",
                    "        if isinstance(other, int):",
                    "            return self.value == other",
                    "        return NotImplemented",
                    "",
                    "    def __repr__(self) -> str:",
                    f'        return f"{class_name}(value={{self.value!r}})"',
                ]
            )
    else:
        maximum = 2 ** type_ir.resolved_width - 1
        mask_msb_byte = (1 << (type_ir.resolved_width % 8)) - 1 if type_ir.resolved_width % 8 else 0xFF
        lines.extend(
            [
                f"    MAX_VALUE = {maximum}",
                "",
                "    def __init__(self, value: bytes | bytearray | int = b'') -> None:",
                "        if isinstance(value, int):",
                "            if value < 0 or value > self.MAX_VALUE:",
                f'                raise ValueError("{class_name} value out of range")',
                '            self.value = value.to_bytes(self.BYTE_COUNT, "big", signed=False)',
                "            return",
                '        if not isinstance(value, (bytes, bytearray)):',
                f'            raise TypeError("{class_name} value must be bytes, bytearray, or int")',
                "        raw = bytes(value)",
                "        if len(raw) == 0:",
                '            raw = b"\\x00" * self.BYTE_COUNT',
                "        if len(raw) != self.BYTE_COUNT:",
                f'            raise ValueError("{class_name} value size mismatch")',
                "        self.value = raw",
                "",
                "    def _to_packed_int(self) -> int:",
                '        return int.from_bytes(self.value, "big", signed=False)',
                "",
                "    @classmethod",
                f'    def _from_packed_int(cls, packed: int) -> "{class_name}":',
                '        return cls(packed.to_bytes(cls.BYTE_COUNT, "big", signed=False))',
                "",
                "    def to_bytes(self) -> bytes:",
                "        return self.value",
                "",
                "    @classmethod",
                f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
                '        if not isinstance(data, (bytes, bytearray)):',
                f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
                "        raw = bytes(data)",
                "        if len(raw) != cls.BYTE_COUNT:",
                f'            raise ValueError("{class_name}.from_bytes size mismatch")',
                "        # Mask padding bits in MSB byte",
                f"        masked = bytes([raw[0] & {mask_msb_byte}]) + raw[1:]",
                "        return cls(masked)",
                "",
                f'    def clone(self) -> "{class_name}":',
                "        return type(self)(self.value)",
                "",
                "    def __eq__(self, other: object) -> bool:",
                "        if isinstance(other, type(self)):",
                "            return self.value == other.value",
                "        if isinstance(other, (bytes, bytearray)):",
                "            return self.value == bytes(other)",
                "        return NotImplemented",
                "",
                "    def __repr__(self) -> str:",
                f'        return f"{class_name}(value={{self.value!r}})"',
            ]
        )
    return lines


def _render_py_struct(*, type_ir: StructIR, type_index: dict[str, TypeDefIR]) -> list[str]:
    """Render a Python struct wrapper class."""
    class_name = _type_class_name(type_ir.name)
    width = _resolved_type_width(type_ir=type_ir, type_index=type_index)
    struct_byte_count = sum(
        _field_byte_count(field_ir=f, type_index=type_index) for f in type_ir.fields
    ) + type_ir.alignment_bits // 8
    lines = [
        "@dataclass",
        f"class {class_name}:",
        f"    WIDTH = {width}",
        f"    BYTE_COUNT = {struct_byte_count}",
    ]
    for field_ir in type_ir.fields:
        lines.append(f"    {field_ir.name}: {_render_py_field_annotation(field_ir=field_ir, type_index=type_index)} = {_render_py_field_default(field_ir=field_ir, type_index=type_index)}")
    lines.append("")
    lines.extend(
        [
            "    def __setattr__(self, name: str, value: object) -> None:",
        ]
    )
    for index, field_ir in enumerate(type_ir.fields):
        prefix = "if" if index == 0 else "elif"
        lines.append(f'        {prefix} name == "{field_ir.name}":')
        lines.append(f"            value = self._coerce_{field_ir.name}(value)")
    lines.extend(
        [
            "        super().__setattr__(name, value)",
            "",
        ]
    )
    for field_ir in type_ir.fields:
        lines.extend(_render_py_struct_field_coercer(owner_name=class_name, field_ir=field_ir, type_index=type_index))
        lines.append("")
    # to_bytes: per-field big-endian serialization
    lines.extend(_render_py_struct_to_bytes(type_ir=type_ir, type_index=type_index))
    lines.append("")
    # from_bytes: per-field big-endian deserialization
    lines.extend(_render_py_struct_from_bytes(type_ir=type_ir, class_name=class_name, type_index=type_index))
    lines.append("")
    lines.extend(
        [
            f'    def clone(self) -> "{class_name}":',
            '        return type(self).from_bytes(self.to_bytes())',
        ]
    )
    return lines


def _render_py_struct_to_bytes(*, type_ir: StructIR, type_index: dict[str, TypeDefIR]) -> list[str]:
    """Render the struct to_bytes method with per-field big-endian serialization."""
    lines = [
        "    def to_bytes(self) -> bytes:",
        "        result = bytearray()",
    ]
    for field_ir in type_ir.fields:
        fbc = _field_byte_count(field_ir=field_ir, type_index=type_index)
        match field_ir.type_ir:
            case TypeRefIR(name=name):
                target = type_index[name]
                if isinstance(target, StructIR):
                    lines.extend(
                        [
                            f"        if self.{field_ir.name} is None:",
                            f'            raise ValueError("{field_ir.name} cannot be None during packing")',
                        ]
                    )
                lines.append(f"        result.extend(self.{field_ir.name}.to_bytes())")
            case ScalarTypeSpecIR(signed=signed, resolved_width=resolved_width):
                if resolved_width <= 64:
                    fw = resolved_width
                    mask = (1 << fw) - 1
                    if signed:
                        lines.extend(
                            [
                                f"        _mask_{field_ir.name} = {mask}",
                                f"        _packed_{field_ir.name} = self.{field_ir.name} & _mask_{field_ir.name}",
                                f"        if self.{field_ir.name} < 0:",
                                f"            _packed_{field_ir.name} |= ((1 << {fbc * 8}) - 1) ^ _mask_{field_ir.name}",
                                f'        result.extend(_packed_{field_ir.name}.to_bytes({fbc}, "big", signed=False))',
                            ]
                        )
                    else:
                        lines.extend(
                            [
                                f"        _packed_{field_ir.name} = self.{field_ir.name} & {mask}",
                                f'        result.extend(_packed_{field_ir.name}.to_bytes({fbc}, "big", signed=False))',
                            ]
                        )
                else:
                    # Wide unsigned scalar stored as bytes, already big-endian
                    lines.append(f"        result.extend(self.{field_ir.name})")
            case _:
                raise ValueError(f"unsupported Python struct field type {type(field_ir.type_ir).__name__}")
    if type_ir.alignment_bits > 0:
        align_bytes = type_ir.alignment_bits // 8
        lines.append(f"        result.extend(b'\\x00' * {align_bytes})")
    lines.append("        return bytes(result)")
    return lines


def _render_py_struct_from_bytes(*, type_ir: StructIR, class_name: str, type_index: dict[str, TypeDefIR]) -> list[str]:
    """Render the struct from_bytes method with per-field big-endian deserialization."""
    lines = [
        "    @classmethod",
        f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
        '        if not isinstance(data, (bytes, bytearray)):',
        f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
        "        raw = bytes(data)",
        "        if len(raw) != cls.BYTE_COUNT:",
        f'            raise ValueError("{class_name}.from_bytes size mismatch")',
        "        obj = cls()",
        "        offset = 0",
    ]
    for field_ir in type_ir.fields:
        fbc = _field_byte_count(field_ir=field_ir, type_index=type_index)
        match field_ir.type_ir:
            case TypeRefIR(name=name):
                target = type_index[name]
                target_class = _type_class_name(target.name)
                lines.extend(
                    [
                        f"        obj.{field_ir.name} = {target_class}.from_bytes(raw[offset:offset + {fbc}])",
                        f"        offset += {fbc}",
                    ]
                )
            case ScalarTypeSpecIR(signed=signed, resolved_width=resolved_width):
                if resolved_width <= 64:
                    fw = resolved_width
                    mask = (1 << fw) - 1
                    if signed:
                        pad_bits = fbc * 8 - fw
                        sign_bit_val = 1 << (fw - 1)
                        lines.extend(
                            [
                                f"        _raw_int_{field_ir.name} = int.from_bytes(raw[offset:offset + {fbc}], \"big\", signed=False)",
                                f"        _data_{field_ir.name} = _raw_int_{field_ir.name} & {mask}",
                                f"        _padding_{field_ir.name} = _raw_int_{field_ir.name} >> {fw}",
                                f"        _sign_bit_{field_ir.name} = (_data_{field_ir.name} >> {fw - 1}) & 1",
                                f"        _expected_padding_{field_ir.name} = ((1 << {pad_bits}) - 1) if _sign_bit_{field_ir.name} else 0",
                                f"        if _padding_{field_ir.name} != _expected_padding_{field_ir.name}:",
                                f'            raise ValueError("{class_name}.from_bytes signed padding mismatch for {field_ir.name}")',
                                f"        obj.{field_ir.name} = _data_{field_ir.name} - {1 << fw} if (_data_{field_ir.name} & {sign_bit_val}) else _data_{field_ir.name}",
                                f"        offset += {fbc}",
                            ]
                        )
                    else:
                        lines.extend(
                            [
                                f"        obj.{field_ir.name} = int.from_bytes(raw[offset:offset + {fbc}], \"big\", signed=False) & {mask}",
                                f"        offset += {fbc}",
                            ]
                        )
                else:
                    # Wide unsigned scalar stored as bytes
                    mask_msb_byte = (1 << (resolved_width % 8)) - 1 if resolved_width % 8 else 0xFF
                    lines.extend(
                        [
                            f"        _wide_raw_{field_ir.name} = raw[offset:offset + {fbc}]",
                            f"        obj.{field_ir.name} = bytes([_wide_raw_{field_ir.name}[0] & {mask_msb_byte}]) + _wide_raw_{field_ir.name}[1:]",
                            f"        offset += {fbc}",
                        ]
                    )
            case _:
                raise ValueError(f"unsupported Python struct field type {type(field_ir.type_ir).__name__}")
    lines.append("        return obj")
    return lines


def _render_py_field_annotation(*, field_ir: StructFieldIR, type_index: dict[str, TypeDefIR]) -> str:
    """Render one Python field annotation."""
    match field_ir.type_ir:
        case TypeRefIR(name=name):
            target = type_index[name]
            class_name = _type_class_name(target.name)
            if isinstance(target, StructIR):
                return f"{class_name} | None"
            return class_name
        case ScalarTypeSpecIR(resolved_width=resolved_width):
            return "int" if resolved_width <= 64 else "bytes"
        case _:
            raise ValueError(f"unsupported Python struct field type {type(field_ir.type_ir).__name__}")


def _render_py_field_default(*, field_ir: StructFieldIR, type_index: dict[str, TypeDefIR]) -> str:
    """Render one Python field default."""
    match field_ir.type_ir:
        case TypeRefIR(name=name):
            return f"field(default_factory={_type_class_name(type_index[name].name)})"
        case ScalarTypeSpecIR(resolved_width=resolved_width):
            if resolved_width <= 64:
                return "0"
            return f'b"\\x00" * {byte_count(resolved_width)}'
        case _:
            raise ValueError(f"unsupported Python struct field type {type(field_ir.type_ir).__name__}")


def _render_py_struct_field_coercer(*, owner_name: str, field_ir: StructFieldIR, type_index: dict[str, TypeDefIR]) -> list[str]:
    """Render one Python field coercion helper."""
    lines = ["    @staticmethod", f"    def _coerce_{field_ir.name}(value: object) -> {_render_py_field_annotation(field_ir=field_ir, type_index=type_index)}:"]
    match field_ir.type_ir:
        case TypeRefIR(name=name):
            target = type_index[name]
            class_name = _type_class_name(target.name)
            if isinstance(target, StructIR):
                lines.extend(
                    [
                        "        if value is None:",
                        "            return None",
                        f"        if isinstance(value, {class_name}):",
                        "            return value",
                        f'        raise TypeError("{owner_name}.{field_ir.name} must be {class_name} or None")',
                    ]
                )
            elif isinstance(target, FlagsIR):
                lines.extend(
                    [
                        f"        if isinstance(value, {class_name}):",
                        "            return value",
                        f'        raise TypeError("{owner_name}.{field_ir.name} must be {class_name}")',
                    ]
                )
            elif isinstance(target, EnumIR):
                lines.extend(
                    [
                        f"        if isinstance(value, {class_name}):",
                        "            return value",
                        f'        raise TypeError("{owner_name}.{field_ir.name} must be {class_name}")',
                    ]
                )
            else:
                lines.extend(
                    [
                        f"        if isinstance(value, {class_name}):",
                        "            return value",
                        f"        return {class_name}(value)",
                    ]
                )
        case ScalarTypeSpecIR(signed=signed, resolved_width=resolved_width):
            if resolved_width <= 64:
                minimum = -(2 ** (resolved_width - 1)) if signed else 0
                maximum = 2 ** (resolved_width - 1) - 1 if signed else 2 ** resolved_width - 1
                lines.extend(
                    [
                        "        if not isinstance(value, int):",
                        f'            raise TypeError("{owner_name}.{field_ir.name} must be int")',
                        f"        if value < {minimum} or value > {maximum}:",
                        f'            raise ValueError("{owner_name}.{field_ir.name} value out of range")',
                        "        return value",
                    ]
                )
            else:
                fbc = byte_count(resolved_width)
                lines.extend(
                    [
                        "        if isinstance(value, bytearray):",
                        "            value = bytes(value)",
                        "        if not isinstance(value, bytes):",
                        f'            raise TypeError("{owner_name}.{field_ir.name} must be bytes")',
                        f"        if len(value) != {fbc}:",
                        f'            raise ValueError("{owner_name}.{field_ir.name} size mismatch")',
                        "        return value",
                    ]
                )
        case _:
            raise ValueError(f"unsupported Python struct field type {type(field_ir.type_ir).__name__}")
    return lines


def _resolved_type_width(*, type_ir: TypeDefIR, type_index: dict[str, TypeDefIR]) -> int:
    """Resolve the data width (in bits) of one type."""
    if isinstance(type_ir, ScalarAliasIR):
        return type_ir.resolved_width
    if isinstance(type_ir, FlagsIR):
        return len(type_ir.fields)
    if isinstance(type_ir, EnumIR):
        return type_ir.resolved_width
    return sum(_resolved_field_width(field_type=field.type_ir, type_index=type_index) for field in type_ir.fields)


def _resolved_field_width(*, field_type: FieldTypeIR, type_index: dict[str, TypeDefIR]) -> int:
    """Resolve the data width (in bits) of one field type."""
    if isinstance(field_type, ScalarTypeSpecIR):
        return field_type.resolved_width
    return _resolved_type_width(type_ir=type_index[field_type.name], type_index=type_index)


def _type_byte_count(*, type_ir: TypeDefIR, type_index: dict[str, TypeDefIR]) -> int:
    """Resolve the byte-aligned byte count of one type (including alignment)."""
    if isinstance(type_ir, ScalarAliasIR):
        return byte_count(type_ir.resolved_width)
    if isinstance(type_ir, FlagsIR):
        return (len(type_ir.fields) + type_ir.alignment_bits) // 8
    if isinstance(type_ir, EnumIR):
        return byte_count(type_ir.resolved_width)
    field_bytes = sum(_field_byte_count(field_ir=f, type_index=type_index) for f in type_ir.fields)
    return field_bytes + type_ir.alignment_bits // 8


def _field_byte_count(*, field_ir: StructFieldIR, type_index: dict[str, TypeDefIR]) -> int:
    """Resolve the byte-aligned byte count of one struct field."""
    match field_ir.type_ir:
        case ScalarTypeSpecIR(resolved_width=resolved_width):
            return byte_count(resolved_width)
        case TypeRefIR(name=name):
            return _type_byte_count(type_ir=type_index[name], type_index=type_index)
        case _:
            raise ValueError(f"unsupported field type {type(field_ir.type_ir).__name__}")



def _type_class_name(type_name: str) -> str:
    """Convert a generated type name to its software wrapper class name."""
    if type_name.endswith("_t"):
        return f"{type_name[:-2]}_ct"
    return f"{type_name}_ct"


# ---------------------------------------------------------------------------
# Enum IntEnum + wrapper class
# ---------------------------------------------------------------------------


def _render_py_enum(*, type_ir: EnumIR) -> list[str]:
    """Render a Python IntEnum subclass and wrapper class for an enum type."""
    base = type_ir.name[:-2] if type_ir.name.endswith("_t") else type_ir.name
    enum_class_name = f"{base}_enum_t"
    class_name = _type_class_name(type_ir.name)
    bc = byte_count(type_ir.resolved_width)
    width = type_ir.resolved_width
    first_member = type_ir.values[0].name if type_ir.values else "0"
    mask = (1 << width) - 1

    lines: list[str] = []

    # IntEnum subclass
    lines.append(f"class {enum_class_name}(IntEnum):")
    for v in type_ir.values:
        lines.append(f"    {v.name} = {v.resolved_value}")
    lines.append("")

    # Wrapper class
    lines.extend([
        f"class {class_name}:",
        f"    WIDTH = {width}",
        f"    BYTE_COUNT = {bc}",
        "",
        f"    def __init__(self, value: {enum_class_name} = {enum_class_name}.{first_member}) -> None:",
        f"        if not isinstance(value, {enum_class_name}):",
        f'            raise TypeError("{class_name} value must be {enum_class_name}")',
        "        self.value = value",
        "",
        "    def to_bytes(self) -> bytes:",
        f'        return int(self.value).to_bytes({bc}, "big", signed=False)',
        "",
        "    @classmethod",
        f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
        "        if not isinstance(data, (bytes, bytearray)):",
        f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
        "        raw = bytes(data)",
        f"        if len(raw) != {bc}:",
        f'            raise ValueError("{class_name}.from_bytes size mismatch")',
        f'        raw_int = int.from_bytes(raw, "big", signed=False) & {mask}',
        "        try:",
        f"            enum_val = {enum_class_name}(raw_int)",
        "        except ValueError:",
        f'            raise ValueError("{class_name}.from_bytes unknown enum value")',
        "        return cls(enum_val)",
        "",
        f'    def clone(self) -> "{class_name}":',
        "        return type(self)(self.value)",
        "",
        "    def __int__(self) -> int:",
        "        return int(self.value)",
        "",
        "    def __index__(self) -> int:",
        "        return int(self.value)",
        "",
        "    def __eq__(self, other: object) -> bool:",
        "        if isinstance(other, type(self)):",
        "            return self.value == other.value",
        "        if isinstance(other, int):",
        "            return int(self.value) == other",
        "        return NotImplemented",
        "",
        "    def __repr__(self) -> str:",
        f'        return f"{class_name}(value={{self.value!r}})"',
    ])
    return lines


# ---------------------------------------------------------------------------
# Flags wrapper class
# ---------------------------------------------------------------------------


def _render_py_flags(*, type_ir: FlagsIR) -> list[str]:
    """Render a Python flags wrapper class."""
    class_name = _type_class_name(type_ir.name)
    num_flags = len(type_ir.fields)
    bc = byte_count(num_flags)
    total_bits = bc * 8
    # Data mask: top num_flags bits set, bottom alignment_bits clear
    data_mask = ((1 << num_flags) - 1) << type_ir.alignment_bits

    lines = [
        f"class {class_name}:",
        f"    WIDTH: int = {num_flags}",
        f"    BYTE_COUNT: int = {bc}",
        "",
        "    def __init__(self) -> None:",
        "        self._value: int = 0",
        "",
    ]

    # Per-flag properties
    for i, flag in enumerate(type_ir.fields):
        mask = 1 << (total_bits - 1 - i)
        lines.extend(
            [
                "    @property",
                f"    def {flag.name}(self) -> bool:",
                f"        return (self._value & {mask}) != 0",
                "",
                f"    @{flag.name}.setter",
                f"    def {flag.name}(self, v: bool) -> None:",
                f"        if v:",
                f"            self._value |= {mask}",
                f"        else:",
                f"            self._value &= ~{mask}",
                "",
            ]
        )

    # to_bytes
    lines.extend(
        [
            "    def to_bytes(self) -> bytes:",
            f'        return (self._value & {data_mask}).to_bytes({bc}, "big")',
            "",
        ]
    )

    # from_bytes
    lines.extend(
        [
            "    @classmethod",
            f'    def from_bytes(cls, data: bytes | bytearray) -> "{class_name}":',
            "        if not isinstance(data, (bytes, bytearray)):",
            f'            raise TypeError("{class_name}.from_bytes expects bytes or bytearray")',
            "        raw = bytes(data)",
            f"        if len(raw) != {bc}:",
            f'            raise ValueError("{class_name}.from_bytes size mismatch")',
            "        obj = cls()",
            f'        obj._value = int.from_bytes(raw, "big") & {data_mask}',
            "        return obj",
            "",
        ]
    )

    # clone
    lines.extend(
        [
            f'    def clone(self) -> "{class_name}":',
            "        obj = self.__class__()",
            f"        obj._value = self._value & {data_mask}",
            "        return obj",
            "",
        ]
    )

    # __eq__
    lines.extend(
        [
            "    def __eq__(self, other: object) -> bool:",
            f"        if not isinstance(other, {class_name}):",
            "            return NotImplemented",
            f"        return (self._value & {data_mask}) == (other._value & {data_mask})",
        ]
    )

    return lines
