"""Python backend.

Renders generated Python modules via Jinja2 templates. The Python
emitter holds no semantic logic; all numeric primitives and
pre-rendered fragments are computed by ``build_module_view_py`` in
``view.py``, and the templates in ``templates/`` render structure
and syntax.
"""

from __future__ import annotations

from pathlib import Path

from piketype.backends.common.headers import render_header
from piketype.backends.common.render import make_environment, render
from piketype.backends.py.view import build_module_view_py
from piketype.config import Config
from piketype.ir.nodes import ModuleIR, RepoIR, TypeDefIR
from piketype.ir.repo_index import build_repo_type_index
from piketype.paths import backend_output_path


def emit_py(repo: RepoIR, *, config: Config) -> list[Path]:
    """Emit Python outputs.

    Each module's output goes to
    ``<py.backend_root>/<sub>/[<py.language_id>/]<name>_types.py``.
    An ``__init__.py`` is created in each output directory so the
    generated module is a regular Python package.

    If the ``py`` backend is not declared in the config, no output is
    produced and the function returns an empty list.
    """
    written_paths: list[Path] = []
    py_backend = config.get_backend("py")
    if py_backend is None:
        return written_paths

    project_root = config.project_root
    piketype_root = config.frontend.piketype_root
    repo_root = Path(repo.repo_root)
    env = make_environment(package="piketype.backends.py")
    repo_type_index = build_repo_type_index(repo)
    for module in repo.modules:
        output_path = backend_output_path(
            backend=py_backend,
            project_root=project_root,
            piketype_root=piketype_root,
            module_path=repo_root / module.ref.repo_relative_path,
            basename_suffix="_types",
            ext=".py",
        )
        output_path.parent.mkdir(parents=True, exist_ok=True)
        _ensure_package_init(output_path.parent, written_paths)
        output_path.write_text(
            _render_module(module=module, env=env, repo_type_index=repo_type_index),
            encoding="utf-8",
        )
        written_paths.append(output_path)
    return written_paths


def _render_module(*, module: ModuleIR, env: object, repo_type_index: dict[tuple[str, str], TypeDefIR]) -> str:
    """Build the view model and render module.j2."""
    header = render_header(source_paths=(module.ref.repo_relative_path,)).replace("//", "#")
    view = build_module_view_py(module=module, header=header, repo_type_index=repo_type_index)
    return render(env=env, template_name="module.j2", context=view)


def _ensure_package_init(package_dir: Path, written_paths: list[Path]) -> None:
    """Create a package ``__init__.py`` if missing."""
    package_dir.mkdir(parents=True, exist_ok=True)
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("# Generated by piketype\n# Do not edit by hand.\n", encoding="utf-8")
        written_paths.append(init_path)
