// Generated by piketype
// Source: action_lookup/piketype/table.py
// Do not edit by hand.

package table_test_pkg;
  import table_pkg::*;

  class addr_ct;
    localparam int WIDTH = LP_ADDR_WIDTH;
    localparam int BYTE_COUNT = LP_ADDR_BYTE_COUNT;
    rand addr_t value;
  
    function new(addr_t value_in = '0);
      value = value_in;
    endfunction
  
    function automatic addr_t to_slv();
      return value;
    endfunction
  
    function void from_slv(addr_t value_in);
      value = value_in;
    endfunction
  
    task automatic to_bytes(output byte unsigned bytes[]);
      logic [31:0] padded;
      bytes = new[BYTE_COUNT];
      padded = '0;
      padded[WIDTH-1:0] = value;
      for (int idx = 0; idx < BYTE_COUNT; idx++) begin
        bytes[idx] = padded[(BYTE_COUNT - 1 - idx)*8 +: 8];
      end
    endtask
  
    function void from_bytes(input byte unsigned bytes[]);
      logic [31:0] padded;
      if (bytes.size() != BYTE_COUNT) begin
        $fatal(1, "addr_ct.from_bytes size mismatch: expected %0d got %0d", BYTE_COUNT, bytes.size());
      end
      padded = '0;
      for (int idx = 0; idx < BYTE_COUNT; idx++) begin
        padded[(BYTE_COUNT - 1 - idx)*8 +: 8] = bytes[idx];
      end
      value = addr_t'(padded[WIDTH-1:0]);
    endfunction
  
    function void copy(input addr_ct rhs);
      value = rhs.value;
    endfunction
  
    function automatic addr_ct clone();
      addr_ct cloned = new();
      cloned.value = value;
      return cloned;
    endfunction
  
    function automatic bit compare(input addr_ct rhs);
      return value === rhs.value;
    endfunction
  
    function automatic string sprint();
      return $sformatf("addr_ct(value=0x%0h)", value);
    endfunction
  endclass : addr_ct

  class coherent_id_ct;
    localparam int WIDTH = LP_COHERENT_ID_WIDTH;
    localparam int BYTE_COUNT = LP_COHERENT_ID_BYTE_COUNT;
    rand coherent_id_t value;
  
    function new(coherent_id_t value_in = '0);
      value = value_in;
    endfunction
  
    function automatic coherent_id_t to_slv();
      return value;
    endfunction
  
    function void from_slv(coherent_id_t value_in);
      value = value_in;
    endfunction
  
    task automatic to_bytes(output byte unsigned bytes[]);
      logic [15:0] padded;
      bytes = new[BYTE_COUNT];
      padded = '0;
      padded[WIDTH-1:0] = value;
      for (int idx = 0; idx < BYTE_COUNT; idx++) begin
        bytes[idx] = padded[(BYTE_COUNT - 1 - idx)*8 +: 8];
      end
    endtask
  
    function void from_bytes(input byte unsigned bytes[]);
      logic [15:0] padded;
      if (bytes.size() != BYTE_COUNT) begin
        $fatal(1, "coherent_id_ct.from_bytes size mismatch: expected %0d got %0d", BYTE_COUNT, bytes.size());
      end
      padded = '0;
      for (int idx = 0; idx < BYTE_COUNT; idx++) begin
        padded[(BYTE_COUNT - 1 - idx)*8 +: 8] = bytes[idx];
      end
      value = coherent_id_t'(padded[WIDTH-1:0]);
    endfunction
  
    function void copy(input coherent_id_ct rhs);
      value = rhs.value;
    endfunction
  
    function automatic coherent_id_ct clone();
      coherent_id_ct cloned = new();
      cloned.value = value;
      return cloned;
    endfunction
  
    function automatic bit compare(input coherent_id_ct rhs);
      return value === rhs.value;
    endfunction
  
    function automatic string sprint();
      return $sformatf("coherent_id_ct(value=0x%0h)", value);
    endfunction
  endclass : coherent_id_ct
endpackage
