// Generated by piketype
// Source: action_lookup/piketype/updates.py
// Do not edit by hand.

package updates_test_pkg;
  import updates_pkg::*;
  import table_pkg::addr_t;
  import table_pkg::coherent_id_t;

  class ll_table_update_ct;
    localparam int WIDTH = LP_LL_TABLE_UPDATE_WIDTH;
    localparam int BYTE_COUNT = LP_LL_TABLE_UPDATE_BYTE_COUNT;
    rand addr_t next_addr;
    rand addr_t action_addr;
    rand coherent_id_t expected_id;
    rand logic not_last;
  
    function new();
      next_addr = '0;
      action_addr = '0;
      expected_id = '0;
      not_last = '0;
    endfunction
  
    function automatic ll_table_update_t to_slv();
      ll_table_update_t packed_value;
      packed_value.next_addr = next_addr;
      packed_value.action_addr = action_addr;
      packed_value.expected_id = expected_id;
      packed_value.not_last = not_last;
      packed_value.not_last_pad = '0;
      packed_value._align_pad = '0;
      return packed_value;
    endfunction
  
    function void from_slv(ll_table_update_t value_in);
      next_addr = value_in.next_addr;
      action_addr = value_in.action_addr;
      expected_id = value_in.expected_id;
      not_last = value_in.not_last;
    endfunction
  
    task automatic to_bytes(output byte unsigned bytes[]);
      int byte_idx;
      bytes = new[BYTE_COUNT];
      byte_idx = 0;
      begin
        logic [31:0] fb;
        fb = '0;
        fb[31:0] = next_addr;
        for (int i = 0; i < 4; i++) bytes[byte_idx + i] = fb[(4 - 1 - i)*8 +: 8];
        byte_idx += 4;
      end
      begin
        logic [31:0] fb;
        fb = '0;
        fb[31:0] = action_addr;
        for (int i = 0; i < 4; i++) bytes[byte_idx + i] = fb[(4 - 1 - i)*8 +: 8];
        byte_idx += 4;
      end
      begin
        logic [15:0] fb;
        fb = '0;
        fb[15:0] = expected_id;
        for (int i = 0; i < 2; i++) bytes[byte_idx + i] = fb[(2 - 1 - i)*8 +: 8];
        byte_idx += 2;
      end
      begin
        logic [7:0] fb;
        fb = '0;
        fb[0:0] = not_last;
        for (int i = 0; i < 1; i++) bytes[byte_idx + i] = fb[(1 - 1 - i)*8 +: 8];
        byte_idx += 1;
      end
      begin
        for (int i = 0; i < 1; i++) bytes[byte_idx + i] = 8'h00;
        byte_idx += 1;
      end
    endtask
  
    function void from_bytes(input byte unsigned bytes[]);
      int byte_idx;
      if (bytes.size() != BYTE_COUNT) begin
        $fatal(1, "ll_table_update_ct.from_bytes size mismatch: expected %0d got %0d", BYTE_COUNT, bytes.size());
      end
      byte_idx = 0;
      begin
        logic [31:0] fb;
        fb = '0;
        for (int i = 0; i < 4; i++) fb[(4 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        next_addr = fb[31:0];
        byte_idx += 4;
      end
      begin
        logic [31:0] fb;
        fb = '0;
        for (int i = 0; i < 4; i++) fb[(4 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        action_addr = fb[31:0];
        byte_idx += 4;
      end
      begin
        logic [15:0] fb;
        fb = '0;
        for (int i = 0; i < 2; i++) fb[(2 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        expected_id = fb[15:0];
        byte_idx += 2;
      end
      begin
        logic [7:0] fb;
        fb = '0;
        for (int i = 0; i < 1; i++) fb[(1 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        not_last = fb[0:0];
        byte_idx += 1;
      end
      byte_idx += 1;
    endfunction
  
    function void copy(input ll_table_update_ct rhs);
      next_addr = rhs.next_addr;
      action_addr = rhs.action_addr;
      expected_id = rhs.expected_id;
      not_last = rhs.not_last;
    endfunction
  
    function automatic ll_table_update_ct clone();
      ll_table_update_ct cloned = new();
      cloned.copy(this);
      return cloned;
    endfunction
  
    function automatic bit compare(input ll_table_update_ct rhs);
      bit match;
      match = 1'b1;
      match &= (next_addr === rhs.next_addr);
      match &= (action_addr === rhs.action_addr);
      match &= (expected_id === rhs.expected_id);
      match &= (not_last === rhs.not_last);
      return match;
    endfunction
  
    function automatic string sprint();
      return $sformatf("ll_table_update_ct(next_addr=0x%0h, action_addr=0x%0h, expected_id=0x%0h, not_last=0x%0h)", next_addr, action_addr, expected_id, not_last);
    endfunction
  endclass : ll_table_update_ct

  class action_ct;
    localparam int WIDTH = LP_ACTION_WIDTH;
    localparam int BYTE_COUNT = LP_ACTION_BYTE_COUNT;
    rand logic [63:0] symbol;
    rand logic signed [63:0] price;
    rand logic signed [63:0] volume;
    rand logic side;
    rand logic [1:0] order_type;
    rand logic [1:0] life_time;
  
    function new();
      symbol = '0;
      price = '0;
      volume = '0;
      side = '0;
      order_type = '0;
      life_time = '0;
    endfunction
  
    function automatic action_t to_slv();
      action_t packed_value;
      packed_value.symbol = symbol;
      packed_value.price = price;
      packed_value.volume = volume;
      packed_value.side = side;
      packed_value.side_pad = '0;
      packed_value.order_type = order_type;
      packed_value.order_type_pad = '0;
      packed_value.life_time = life_time;
      packed_value.life_time_pad = '0;
      return packed_value;
    endfunction
  
    function void from_slv(action_t value_in);
      symbol = value_in.symbol;
      price = value_in.price;
      volume = value_in.volume;
      side = value_in.side;
      order_type = value_in.order_type;
      life_time = value_in.life_time;
    endfunction
  
    task automatic to_bytes(output byte unsigned bytes[]);
      int byte_idx;
      bytes = new[BYTE_COUNT];
      byte_idx = 0;
      begin
        logic [63:0] fb;
        fb = '0;
        fb[63:0] = symbol;
        for (int i = 0; i < 8; i++) bytes[byte_idx + i] = fb[(8 - 1 - i)*8 +: 8];
        byte_idx += 8;
      end
      begin
        logic [63:0] fb;
        fb = '0;
        fb[63:0] = price;
        for (int i = 0; i < 8; i++) bytes[byte_idx + i] = fb[(8 - 1 - i)*8 +: 8];
        byte_idx += 8;
      end
      begin
        logic [63:0] fb;
        fb = '0;
        fb[63:0] = volume;
        for (int i = 0; i < 8; i++) bytes[byte_idx + i] = fb[(8 - 1 - i)*8 +: 8];
        byte_idx += 8;
      end
      begin
        logic [7:0] fb;
        fb = '0;
        fb[0:0] = side;
        for (int i = 0; i < 1; i++) bytes[byte_idx + i] = fb[(1 - 1 - i)*8 +: 8];
        byte_idx += 1;
      end
      begin
        logic [7:0] fb;
        fb = '0;
        fb[1:0] = order_type;
        for (int i = 0; i < 1; i++) bytes[byte_idx + i] = fb[(1 - 1 - i)*8 +: 8];
        byte_idx += 1;
      end
      begin
        logic [7:0] fb;
        fb = '0;
        fb[1:0] = life_time;
        for (int i = 0; i < 1; i++) bytes[byte_idx + i] = fb[(1 - 1 - i)*8 +: 8];
        byte_idx += 1;
      end
    endtask
  
    function void from_bytes(input byte unsigned bytes[]);
      int byte_idx;
      if (bytes.size() != BYTE_COUNT) begin
        $fatal(1, "action_ct.from_bytes size mismatch: expected %0d got %0d", BYTE_COUNT, bytes.size());
      end
      byte_idx = 0;
      begin
        logic [63:0] fb;
        fb = '0;
        for (int i = 0; i < 8; i++) fb[(8 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        symbol = fb[63:0];
        byte_idx += 8;
      end
      begin
        logic [63:0] fb;
        fb = '0;
        for (int i = 0; i < 8; i++) fb[(8 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        price = fb[63:0];
        byte_idx += 8;
      end
      begin
        logic [63:0] fb;
        fb = '0;
        for (int i = 0; i < 8; i++) fb[(8 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        volume = fb[63:0];
        byte_idx += 8;
      end
      begin
        logic [7:0] fb;
        fb = '0;
        for (int i = 0; i < 1; i++) fb[(1 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        side = fb[0:0];
        byte_idx += 1;
      end
      begin
        logic [7:0] fb;
        fb = '0;
        for (int i = 0; i < 1; i++) fb[(1 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        order_type = fb[1:0];
        byte_idx += 1;
      end
      begin
        logic [7:0] fb;
        fb = '0;
        for (int i = 0; i < 1; i++) fb[(1 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        life_time = fb[1:0];
        byte_idx += 1;
      end
    endfunction
  
    function void copy(input action_ct rhs);
      symbol = rhs.symbol;
      price = rhs.price;
      volume = rhs.volume;
      side = rhs.side;
      order_type = rhs.order_type;
      life_time = rhs.life_time;
    endfunction
  
    function automatic action_ct clone();
      action_ct cloned = new();
      cloned.copy(this);
      return cloned;
    endfunction
  
    function automatic bit compare(input action_ct rhs);
      bit match;
      match = 1'b1;
      match &= (symbol === rhs.symbol);
      match &= (price === rhs.price);
      match &= (volume === rhs.volume);
      match &= (side === rhs.side);
      match &= (order_type === rhs.order_type);
      match &= (life_time === rhs.life_time);
      return match;
    endfunction
  
    function automatic string sprint();
      return $sformatf("action_ct(symbol=0x%0h, price=0x%0h, volume=0x%0h, side=0x%0h, order_type=0x%0h, life_time=0x%0h)", symbol, price, volume, side, order_type, life_time);
    endfunction
  endclass : action_ct

  class action_table_update_ct;
    localparam int WIDTH = LP_ACTION_TABLE_UPDATE_WIDTH;
    localparam int BYTE_COUNT = LP_ACTION_TABLE_UPDATE_BYTE_COUNT;
    rand coherent_id_t stored_id;
    action_ct action;
  
    function new();
      stored_id = '0;
      action = new();
    endfunction
  
    function automatic action_table_update_t to_slv();
      action_table_update_t packed_value;
      packed_value.stored_id = stored_id;
      packed_value.action = action.to_slv();
      packed_value._align_pad = '0;
      return packed_value;
    endfunction
  
    function void from_slv(action_table_update_t value_in);
      stored_id = value_in.stored_id;
      action.from_slv(value_in.action);
    endfunction
  
    task automatic to_bytes(output byte unsigned bytes[]);
      int byte_idx;
      bytes = new[BYTE_COUNT];
      byte_idx = 0;
      begin
        logic [15:0] fb;
        fb = '0;
        fb[15:0] = stored_id;
        for (int i = 0; i < 2; i++) bytes[byte_idx + i] = fb[(2 - 1 - i)*8 +: 8];
        byte_idx += 2;
      end
      begin
        byte unsigned field_bytes[];
        action.to_bytes(field_bytes);
        for (int i = 0; i < 27; i++) bytes[byte_idx + i] = field_bytes[i];
        byte_idx += 27;
      end
      begin
        for (int i = 0; i < 3; i++) bytes[byte_idx + i] = 8'h00;
        byte_idx += 3;
      end
    endtask
  
    function void from_bytes(input byte unsigned bytes[]);
      int byte_idx;
      if (bytes.size() != BYTE_COUNT) begin
        $fatal(1, "action_table_update_ct.from_bytes size mismatch: expected %0d got %0d", BYTE_COUNT, bytes.size());
      end
      byte_idx = 0;
      begin
        logic [15:0] fb;
        fb = '0;
        for (int i = 0; i < 2; i++) fb[(2 - 1 - i)*8 +: 8] = bytes[byte_idx + i];
        stored_id = fb[15:0];
        byte_idx += 2;
      end
      begin
        byte unsigned field_bytes[] = new[27];
        for (int i = 0; i < 27; i++) field_bytes[i] = bytes[byte_idx + i];
        action.from_bytes(field_bytes);
        byte_idx += 27;
      end
      byte_idx += 3;
    endfunction
  
    function void copy(input action_table_update_ct rhs);
      stored_id = rhs.stored_id;
      action.copy(rhs.action);
    endfunction
  
    function automatic action_table_update_ct clone();
      action_table_update_ct cloned = new();
      cloned.copy(this);
      return cloned;
    endfunction
  
    function automatic bit compare(input action_table_update_ct rhs);
      bit match;
      match = 1'b1;
      match &= (stored_id === rhs.stored_id);
      match &= action.compare(rhs.action);
      return match;
    endfunction
  
    function automatic string sprint();
      return $sformatf("action_table_update_ct(stored_id=0x%0h, action=%s)", stored_id, action.sprint());
    endfunction
  endclass : action_table_update_ct
endpackage
