# Generated by piketype
# Source: action_lookup/piketype/updates.py
# Do not edit by hand.

from __future__ import annotations

from dataclasses import dataclass, field

from .table_types import Addr
from .table_types import CoherentId

@dataclass
class LlTableUpdate:
    WIDTH = 81
    BYTE_COUNT = 12
    next_addr: Addr = field(default_factory=Addr)
    action_addr: Addr = field(default_factory=Addr)
    expected_id: CoherentId = field(default_factory=CoherentId)
    not_last: int = 0

    def __setattr__(self, name: str, value: object) -> None:
        if name == "next_addr":
            value = self._coerce_next_addr(value)
        elif name == "action_addr":
            value = self._coerce_action_addr(value)
        elif name == "expected_id":
            value = self._coerce_expected_id(value)
        elif name == "not_last":
            value = self._coerce_not_last(value)
        super().__setattr__(name, value)

    @staticmethod
    def _coerce_next_addr(value: object) -> Addr:
        if isinstance(value, Addr):
            return value
        return Addr(value)

    @staticmethod
    def _coerce_action_addr(value: object) -> Addr:
        if isinstance(value, Addr):
            return value
        return Addr(value)

    @staticmethod
    def _coerce_expected_id(value: object) -> CoherentId:
        if isinstance(value, CoherentId):
            return value
        return CoherentId(value)

    @staticmethod
    def _coerce_not_last(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("LlTableUpdate.not_last must be int")
        if value < 0 or value > 1:
            raise ValueError("LlTableUpdate.not_last value out of range")
        return value

    def pack(self) -> int:
        result = 0
        result = (result << 32) | self.next_addr.pack()
        result = (result << 32) | self.action_addr.pack()
        result = (result << 16) | self.expected_id.pack()
        result = (result << 1) | (self.not_last & 1)
        return result

    @classmethod
    def unpack(cls, packed: int) -> "LlTableUpdate":
        obj = cls()
        obj.next_addr = Addr.unpack((packed >> 49) & 4294967295)
        obj.action_addr = Addr.unpack((packed >> 17) & 4294967295)
        obj.expected_id = CoherentId.unpack((packed >> 1) & 65535)
        obj.not_last = (packed >> 0) & 1
        return obj

    def to_lv(self) -> int:
        return int.from_bytes(self.to_bytes(), "big", signed=False)

    @classmethod
    def from_lv(cls, value: int) -> "LlTableUpdate":
        return cls.from_bytes((value & ((1 << (cls.BYTE_COUNT * 8)) - 1)).to_bytes(cls.BYTE_COUNT, "big", signed=False))

    def to_bytes(self) -> bytes:
        result = bytearray()
        result.extend(self.next_addr.to_bytes())
        result.extend(self.action_addr.to_bytes())
        result.extend(self.expected_id.to_bytes())
        _packed_not_last = self.not_last & 1
        result.extend(_packed_not_last.to_bytes(1, "big", signed=False))
        result.extend(b'\x00' * 1)
        return bytes(result)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "LlTableUpdate":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("LlTableUpdate.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("LlTableUpdate.from_bytes size mismatch")
        obj = cls()
        offset = 0
        obj.next_addr = Addr.from_bytes(raw[offset:offset + 4])
        offset += 4
        obj.action_addr = Addr.from_bytes(raw[offset:offset + 4])
        offset += 4
        obj.expected_id = CoherentId.from_bytes(raw[offset:offset + 2])
        offset += 2
        obj.not_last = int.from_bytes(raw[offset:offset + 1], "big", signed=False) & 1
        offset += 1
        return obj

    def clone(self) -> "LlTableUpdate":
        return type(self).from_bytes(self.to_bytes())

    def compare(self, other: object, msg: str = "") -> None:
        assert isinstance(other, LlTableUpdate), "Expected LlTableUpdate, got " + str(type(other))
        diffs = []
        if self.next_addr != other.next_addr:
            diffs.append("next_addr: expected {!r}, got {!r}".format(self.next_addr, other.next_addr))
        if self.action_addr != other.action_addr:
            diffs.append("action_addr: expected {!r}, got {!r}".format(self.action_addr, other.action_addr))
        if self.expected_id != other.expected_id:
            diffs.append("expected_id: expected {!r}, got {!r}".format(self.expected_id, other.expected_id))
        if self.not_last != other.not_last:
            diffs.append("not_last: expected 0x{:01x}, got 0x{:01x}".format(self.not_last, other.not_last))
        if diffs:
            prefix = msg + ": " if msg else ""
            raise AssertionError(prefix + repr(self) + " != " + repr(other) + " — " + ", ".join(diffs))

@dataclass
class Action:
    WIDTH = 197
    BYTE_COUNT = 27
    symbol: int = 0
    price: int = 0
    volume: int = 0
    side: int = 0
    order_type: int = 0
    life_time: int = 0

    def __setattr__(self, name: str, value: object) -> None:
        if name == "symbol":
            value = self._coerce_symbol(value)
        elif name == "price":
            value = self._coerce_price(value)
        elif name == "volume":
            value = self._coerce_volume(value)
        elif name == "side":
            value = self._coerce_side(value)
        elif name == "order_type":
            value = self._coerce_order_type(value)
        elif name == "life_time":
            value = self._coerce_life_time(value)
        super().__setattr__(name, value)

    @staticmethod
    def _coerce_symbol(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("Action.symbol must be int")
        if value < 0 or value > 18446744073709551615:
            raise ValueError("Action.symbol value out of range")
        return value

    @staticmethod
    def _coerce_price(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("Action.price must be int")
        if value < -9223372036854775808 or value > 9223372036854775807:
            raise ValueError("Action.price value out of range")
        return value

    @staticmethod
    def _coerce_volume(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("Action.volume must be int")
        if value < -9223372036854775808 or value > 9223372036854775807:
            raise ValueError("Action.volume value out of range")
        return value

    @staticmethod
    def _coerce_side(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("Action.side must be int")
        if value < 0 or value > 1:
            raise ValueError("Action.side value out of range")
        return value

    @staticmethod
    def _coerce_order_type(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("Action.order_type must be int")
        if value < 0 or value > 3:
            raise ValueError("Action.order_type value out of range")
        return value

    @staticmethod
    def _coerce_life_time(value: object) -> int:
        if not isinstance(value, int):
            raise TypeError("Action.life_time must be int")
        if value < 0 or value > 3:
            raise ValueError("Action.life_time value out of range")
        return value

    def pack(self) -> int:
        result = 0
        result = (result << 64) | (self.symbol & 18446744073709551615)
        result = (result << 64) | (self.price & 18446744073709551615)
        result = (result << 64) | (self.volume & 18446744073709551615)
        result = (result << 1) | (self.side & 1)
        result = (result << 2) | (self.order_type & 3)
        result = (result << 2) | (self.life_time & 3)
        return result

    @classmethod
    def unpack(cls, packed: int) -> "Action":
        obj = cls()
        obj.symbol = (packed >> 133) & 18446744073709551615
        _slice_price = (packed >> 69) & 18446744073709551615
        obj.price = _slice_price - 18446744073709551616 if (_slice_price & 9223372036854775808) else _slice_price
        _slice_volume = (packed >> 5) & 18446744073709551615
        obj.volume = _slice_volume - 18446744073709551616 if (_slice_volume & 9223372036854775808) else _slice_volume
        obj.side = (packed >> 4) & 1
        obj.order_type = (packed >> 2) & 3
        obj.life_time = (packed >> 0) & 3
        return obj

    def to_lv(self) -> int:
        return int.from_bytes(self.to_bytes(), "big", signed=False)

    @classmethod
    def from_lv(cls, value: int) -> "Action":
        return cls.from_bytes((value & ((1 << (cls.BYTE_COUNT * 8)) - 1)).to_bytes(cls.BYTE_COUNT, "big", signed=False))

    def to_bytes(self) -> bytes:
        result = bytearray()
        _packed_symbol = self.symbol & 18446744073709551615
        result.extend(_packed_symbol.to_bytes(8, "big", signed=False))
        _mask_price = 18446744073709551615
        _packed_price = self.price & _mask_price
        if self.price < 0:
            _packed_price |= ((1 << 64) - 1) ^ _mask_price
        result.extend(_packed_price.to_bytes(8, "big", signed=False))
        _mask_volume = 18446744073709551615
        _packed_volume = self.volume & _mask_volume
        if self.volume < 0:
            _packed_volume |= ((1 << 64) - 1) ^ _mask_volume
        result.extend(_packed_volume.to_bytes(8, "big", signed=False))
        _packed_side = self.side & 1
        result.extend(_packed_side.to_bytes(1, "big", signed=False))
        _packed_order_type = self.order_type & 3
        result.extend(_packed_order_type.to_bytes(1, "big", signed=False))
        _packed_life_time = self.life_time & 3
        result.extend(_packed_life_time.to_bytes(1, "big", signed=False))
        return bytes(result)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "Action":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("Action.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("Action.from_bytes size mismatch")
        obj = cls()
        offset = 0
        obj.symbol = int.from_bytes(raw[offset:offset + 8], "big", signed=False) & 18446744073709551615
        offset += 8
        _raw_int_price = int.from_bytes(raw[offset:offset + 8], "big", signed=False)
        _data_price = _raw_int_price & 18446744073709551615
        _padding_price = _raw_int_price >> 64
        _sign_bit_price = (_data_price >> 63) & 1
        _expected_padding_price = ((1 << 0) - 1) if _sign_bit_price else 0
        if _padding_price != _expected_padding_price:
            raise ValueError("Action.from_bytes signed padding mismatch for price")
        obj.price = _data_price - 18446744073709551616 if (_data_price & 9223372036854775808) else _data_price
        offset += 8
        _raw_int_volume = int.from_bytes(raw[offset:offset + 8], "big", signed=False)
        _data_volume = _raw_int_volume & 18446744073709551615
        _padding_volume = _raw_int_volume >> 64
        _sign_bit_volume = (_data_volume >> 63) & 1
        _expected_padding_volume = ((1 << 0) - 1) if _sign_bit_volume else 0
        if _padding_volume != _expected_padding_volume:
            raise ValueError("Action.from_bytes signed padding mismatch for volume")
        obj.volume = _data_volume - 18446744073709551616 if (_data_volume & 9223372036854775808) else _data_volume
        offset += 8
        obj.side = int.from_bytes(raw[offset:offset + 1], "big", signed=False) & 1
        offset += 1
        obj.order_type = int.from_bytes(raw[offset:offset + 1], "big", signed=False) & 3
        offset += 1
        obj.life_time = int.from_bytes(raw[offset:offset + 1], "big", signed=False) & 3
        offset += 1
        return obj

    def clone(self) -> "Action":
        return type(self).from_bytes(self.to_bytes())

    def compare(self, other: object, msg: str = "") -> None:
        assert isinstance(other, Action), "Expected Action, got " + str(type(other))
        diffs = []
        if self.symbol != other.symbol:
            diffs.append("symbol: expected 0x{:016x}, got 0x{:016x}".format(self.symbol, other.symbol))
        if self.price != other.price:
            diffs.append("price: expected {}, got {}".format(self.price, other.price))
        if self.volume != other.volume:
            diffs.append("volume: expected {}, got {}".format(self.volume, other.volume))
        if self.side != other.side:
            diffs.append("side: expected 0x{:01x}, got 0x{:01x}".format(self.side, other.side))
        if self.order_type != other.order_type:
            diffs.append("order_type: expected 0x{:01x}, got 0x{:01x}".format(self.order_type, other.order_type))
        if self.life_time != other.life_time:
            diffs.append("life_time: expected 0x{:01x}, got 0x{:01x}".format(self.life_time, other.life_time))
        if diffs:
            prefix = msg + ": " if msg else ""
            raise AssertionError(prefix + repr(self) + " != " + repr(other) + " — " + ", ".join(diffs))

@dataclass
class ActionTableUpdate:
    WIDTH = 213
    BYTE_COUNT = 32
    stored_id: CoherentId = field(default_factory=CoherentId)
    action: Action | None = field(default_factory=Action)

    def __setattr__(self, name: str, value: object) -> None:
        if name == "stored_id":
            value = self._coerce_stored_id(value)
        elif name == "action":
            value = self._coerce_action(value)
        super().__setattr__(name, value)

    @staticmethod
    def _coerce_stored_id(value: object) -> CoherentId:
        if isinstance(value, CoherentId):
            return value
        return CoherentId(value)

    @staticmethod
    def _coerce_action(value: object) -> Action | None:
        if value is None:
            return None
        if isinstance(value, Action):
            return value
        raise TypeError("ActionTableUpdate.action must be Action or None")

    def pack(self) -> int:
        result = 0
        result = (result << 16) | self.stored_id.pack()
        if self.action is None:
            raise ValueError("action cannot be None during packing")
        result = (result << 197) | self.action.pack()
        return result

    @classmethod
    def unpack(cls, packed: int) -> "ActionTableUpdate":
        obj = cls()
        obj.stored_id = CoherentId.unpack((packed >> 197) & 65535)
        obj.action = Action.unpack((packed >> 0) & 200867255532373784442745261542645325315275374222849104412671)
        return obj

    def to_lv(self) -> int:
        return int.from_bytes(self.to_bytes(), "big", signed=False)

    @classmethod
    def from_lv(cls, value: int) -> "ActionTableUpdate":
        return cls.from_bytes((value & ((1 << (cls.BYTE_COUNT * 8)) - 1)).to_bytes(cls.BYTE_COUNT, "big", signed=False))

    def to_bytes(self) -> bytes:
        result = bytearray()
        result.extend(self.stored_id.to_bytes())
        if self.action is None:
            raise ValueError("action cannot be None during packing")
        result.extend(self.action.to_bytes())
        result.extend(b'\x00' * 3)
        return bytes(result)

    @classmethod
    def from_bytes(cls, data: bytes | bytearray) -> "ActionTableUpdate":
        if not isinstance(data, (bytes, bytearray)):
            raise TypeError("ActionTableUpdate.from_bytes expects bytes or bytearray")
        raw = bytes(data)
        if len(raw) != cls.BYTE_COUNT:
            raise ValueError("ActionTableUpdate.from_bytes size mismatch")
        obj = cls()
        offset = 0
        obj.stored_id = CoherentId.from_bytes(raw[offset:offset + 2])
        offset += 2
        obj.action = Action.from_bytes(raw[offset:offset + 27])
        offset += 27
        return obj

    def clone(self) -> "ActionTableUpdate":
        return type(self).from_bytes(self.to_bytes())

    def compare(self, other: object, msg: str = "") -> None:
        assert isinstance(other, ActionTableUpdate), "Expected ActionTableUpdate, got " + str(type(other))
        diffs = []
        if self.stored_id != other.stored_id:
            diffs.append("stored_id: expected {!r}, got {!r}".format(self.stored_id, other.stored_id))
        if self.action is None or other.action is None:
            if self.action is not other.action:
                diffs.append("action: expected {!r}, got {!r}".format(self.action, other.action))
        elif self.action != other.action:
            diffs.append("action: expected {!r}, got {!r}".format(self.action, other.action))
        if diffs:
            prefix = msg + ": " if msg else ""
            raise AssertionError(prefix + repr(self) + " != " + repr(other) + " — " + ", ".join(diffs))
